fix(yaml): fixed the cr name in pooling job util
Signed-off-by: w3aman <aman.gupta@mayadata.io>

diff --git a/pipeline/utils/e2e_job_runner b/pipeline/utils/e2e_job_runner
--- a/pipeline/utils/e2e_job_runner
+++ b/pipeline/utils/e2e_job_runner
@@ -4,15 +4,15 @@ job_retry_count=0
 pod_retry_count=0
 container_retry_count=0
 job_state_retry_count=0
-e2e_job_label_key=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 1)
-e2e_job_label_value=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 2)
-e2e_job_file=$(echo $2 | cut -d "=" -f 2)
+lvme2e_job_label_key=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 1)
+lvme2e_job_label_value=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 2)
+lvme2e_job_file=$(echo $2 | cut -d "=" -f 2)
 
 echo "Running the lvm e2e test.."
 
-jobNameCmd="kubectl get jobs -n e2e --no-headers -o jsonpath='{.items[?(@.metadata.labels.${e2e_job_label_key}==\"${e2e_job_label_value}\")].metadata.name}'"
+jobNameCmd="kubectl get jobs -n e2e --no-headers -o jsonpath='{.items[?(@.metadata.labels.${lvme2e_job_label_key}==\"${lvme2e_job_label_value}\")].metadata.name}'"
 
-job_deploy_out=$(kubectl create -f ${e2e_job_file}) && \
+job_deploy_out=$(kubectl create -f ${lvme2e_job_file}) && \
 job_name=$(eval ${jobNameCmd}); retcode=$?
 
 while [ -z "$job_name" ]; do
@@ -24,31 +24,31 @@ while [ -z "$job_name" ]; do
   job_name=$(eval ${jobNameCmd});
 done
 chmod 755 ../pipeline/utils/error_handler
-bash ../pipeline/utils/error_handler ${retcode} msg="Unable to run e2e-test, exiting" action="exit"
+bash ../pipeline/utils/error_handler ${retcode} msg="Unable to run lvme2e-test, exiting" action="exit"
     
-## Obtain the e2e-test pod name 
+## Obtain the lvme2e-test pod name 
 
-e2ePodCmd="kubectl get pod --no-headers -n e2e -o jsonpath='{.items[?(@.metadata.labels.job-name==\"${job_name}\")].metadata.name}'"
-e2e_pod=$(eval ${e2ePodCmd}); retcode=$?
-while [ -z "$e2e_pod" ]; do
+lvme2ePodCmd="kubectl get pod --no-headers -n e2e -o jsonpath='{.items[?(@.metadata.labels.job-name==\"${job_name}\")].metadata.name}'"
+lvme2e_pod=$(eval ${lvme2ePodCmd}); retcode=$?
+while [ -z "$lvme2e_pod" ]; do
   sleep 15
   pod_retry_count=$((pod_retry_count+1))
     if [[ "$pod_retry_count" -eq "15" ]]; then
       echo "unable to get POD_NAME"; exit 1;
     fi
-  pod_name=$(eval ${e2ePodCmd});
+  pod_name=$(eval ${lvme2ePodCmd});
 done
 
-bash ../pipeline/utils/error_handler ${retcode} msg="Unable to find e2e test runner pod, exiting" action="exit"
+bash ../pipeline/utils/error_handler ${retcode} msg="Unable to find lvme2e test runner pod, exiting" action="exit"
 
 ## Wait till the ansibletest container terminates && also confirm job completion status. This is done to ensure
 ## that execution of auxiliary containers such as loggers is completed. Getting the ansibletest ccontainer to completed state 
 ## satisfies the "necessary" condition for test job completion
 
-containerStateCmd="kubectl get pod ${e2e_pod} -n e2e -o jsonpath='{.status.containerStatuses[?(@.name==\"ansibletest\")].state}'"
-jobStateCmd="kubectl get pod ${e2e_pod} --no-headers -n e2e -o custom-columns=:status.phase"
+containerStateCmd="kubectl get pod ${lvme2e_pod} -n e2e -o jsonpath='{.status.containerStatuses[?(@.name==\"ansibletest\")].state}'"
+jobStateCmd="kubectl get pod ${lvme2e_pod} --no-headers -n e2e -o custom-columns=:status.phase"
 
-## TODO: Consider cases where e2e-test pod is evicted
+## TODO: Consider cases where lvme2e-test pod is evicted
 
 while true; do
   cstate=$(eval ${containerStateCmd}); rc=$?
@@ -64,7 +64,7 @@ while true; do
       else break;
       fi
     else
-      echo "unable to get e2e-test container status"; exit 1
+      echo "unable to get lvme2e-test container status"; exit 1
     fi
   fi
 done
@@ -80,11 +80,11 @@ while true; do
     sleep 10
     job_state_retry_count=$((job_state_retry_count+1))
     if [[ "$job_state_retry_count" -eq "10" ]]; then
-      echo "unable to get e2e-test job status"; exit 1;
+      echo "unable to get lvme2e-test job status"; exit 1;
     fi  
   fi
 done
-echo "e2e-test run Job has completed"
+echo "lvme2e-test run Job has completed"
 
-echo "Dumping e2e-test pod logs for debug"; echo ""
-kubectl logs $e2e_pod -n e2e -c ansibletest
+echo "Dumping lvme2e-test pod logs for debug"; echo ""
+kubectl logs $lvme2e_pod -n e2e -c ansibletest
